
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox2;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button button5;

	private global::Gtk.Label file_name;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label lexemes;

	private global::Gtk.Label syymbol_table;

	private global::Gtk.HBox hbox3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.Table table1;

	private global::Gtk.Label classification_column;

	private global::Gtk.Label lexeme_column;

	private global::Gtk.VScrollbar lexeme_scrollbar;

	private global::Gtk.Table table2;

	private global::Gtk.Label identifier_column;

	private global::Gtk.Label value_column;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label execute;

	private global::Gtk.HSeparator hseparator1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("ArnoldC Interpreter");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 139;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Choose FIle");
		this.hbox4.Add(this.button5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.file_name = new global::Gtk.Label();
		this.file_name.WidthRequest = 148;
		this.file_name.Name = "file_name";
		this.file_name.LabelProp = global::Mono.Unix.Catalog.GetString("No file chosen");
		this.hbox4.Add(this.file_name);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.file_name]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.hbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lexemes = new global::Gtk.Label();
		this.lexemes.WidthRequest = 278;
		this.lexemes.Name = "lexemes";
		this.lexemes.LabelProp = global::Mono.Unix.Catalog.GetString("LEXEMES");
		this.hbox5.Add(this.lexemes);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.lexemes]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.syymbol_table = new global::Gtk.Label();
		this.syymbol_table.WidthRequest = 289;
		this.syymbol_table.Name = "syymbol_table";
		this.syymbol_table.LabelProp = global::Mono.Unix.Catalog.GetString("SYMBOL TABLE");
		this.hbox5.Add(this.syymbol_table);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.syymbol_table]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox5]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.WidthRequest = 0;
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add(this.textview1);
		this.hbox3.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow]));
		w9.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.classification_column = new global::Gtk.Label();
		this.classification_column.WidthRequest = 131;
		this.classification_column.Name = "classification_column";
		this.classification_column.LabelProp = global::Mono.Unix.Catalog.GetString("Classification");
		this.table1.Add(this.classification_column);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.classification_column]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lexeme_column = new global::Gtk.Label();
		this.lexeme_column.WidthRequest = 117;
		this.lexeme_column.Name = "lexeme_column";
		this.lexeme_column.LabelProp = global::Mono.Unix.Catalog.GetString("Lexeme");
		this.table1.Add(this.lexeme_column);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.lexeme_column]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox3.Add(this.table1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.table1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lexeme_scrollbar = new global::Gtk.VScrollbar(null);
		this.lexeme_scrollbar.Name = "lexeme_scrollbar";
		this.lexeme_scrollbar.Adjustment.Upper = 100D;
		this.lexeme_scrollbar.Adjustment.PageIncrement = 10D;
		this.lexeme_scrollbar.Adjustment.PageSize = 10D;
		this.lexeme_scrollbar.Adjustment.StepIncrement = 1D;
		this.hbox3.Add(this.lexeme_scrollbar);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lexeme_scrollbar]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.identifier_column = new global::Gtk.Label();
		this.identifier_column.WidthRequest = 132;
		this.identifier_column.Name = "identifier_column";
		this.identifier_column.LabelProp = global::Mono.Unix.Catalog.GetString("Identifier");
		this.table2.Add(this.identifier_column);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.identifier_column]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.value_column = new global::Gtk.Label();
		this.value_column.WidthRequest = 141;
		this.value_column.Name = "value_column";
		this.value_column.LabelProp = global::Mono.Unix.Catalog.GetString("Value");
		this.table2.Add(this.value_column);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.value_column]));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox3.Add(this.table2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.table2]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w17.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.execute = new global::Gtk.Label();
		this.execute.Name = "execute";
		this.execute.LabelProp = global::Mono.Unix.Catalog.GetString("EXECUTE");
		this.vbox4.Add(this.execute);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.execute]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox3.Add(this.vbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
		w20.Position = 2;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 872;
		this.DefaultHeight = 492;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
